# -*- coding: utf-8 -*-
# _regen.py — recreate translate.py with smart paragraph merging
import sys
NL = chr(10)
Q = chr(39)
DQ = chr(34)
SP = DQ + ' ' + DQ
def line(s): L.append(s)
L = []
line('# -*- coding: utf-8 -*-')
line('# translate.py - 英中翻译 EPUB (Qwen3-8B + Ollama, 128K ctx, think=False)')
line('import sys, io, json, time, re, argparse, urllib.request, urllib.error')
line('from pathlib import Path')
line('from ebooklib import epub')
line('from bs4 import BeautifulSoup')
line('')
line('if sys.stdout.encoding and sys.stdout.encoding.lower().startswith(' + DQ + 'gbk' + DQ + '):')
line('    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding=' + DQ + 'utf-8' + DQ + ', errors=' + DQ + 'replace' + DQ + ')')
line('    sys.stderr = sys.stdout')
line('')
line('EPUB_PATH = r' + DQ + 'D:\\personalprofile\\电子书\\大雁塔\\One Thousand Ways to Make 1000 (F.C. Minaker) (z-library.sk, 1lib.sk, z-lib.sk).epub' + DQ)
line('OUTPUT_DIR = Path(r' + DQ + 'D:\\personalprofile\\电子书\\大雁塔\\translate_epub\\output' + DQ + ')')
line('CHAPTERS_DIR = OUTPUT_DIR / ' + DQ + 'chapters' + DQ)
line('IMAGES_DIR = OUTPUT_DIR / ' + DQ + 'images' + DQ)
line('PROGRESS_FILE = OUTPUT_DIR / ' + DQ + 'progress.json' + DQ)
line('OLLAMA_BASE = ' + DQ + 'http://127.0.0.1:11434' + DQ)
line('MODEL_NAME = ' + DQ + 'modelscope.cn/Qwen/Qwen3-8B-GGUF:latest' + DQ)
line('NUM_CTX = 131072')
line('TEMPERATURE = 0.3')
line('SYS = ' + DQ + '你是英中翻译，专译 1930-1940 美国商业自助书。要求：1.直译为主；2.专名首次加注中文；3.商业术语用现代汉语；4.必要时加[译者注]；5.直接输出，不要思考或前言。仅输出译文。' + DQ)
line('')
line('def strip_think(text):')
line('    return re.sub(' + DQ + r'<think>.*?</think>' + DQ + ', ' + DQ + DQ + ', text, flags=re.DOTALL).strip()')
line('')
line('def translate_one(text, retries=3):')
line('    if not text or not text.strip(): return text')
line('    payload = json.dumps({' + DQ + 'model' + DQ + ': MODEL_NAME, ' + DQ + 'messages' + DQ + ': [{' + DQ + 'role' + DQ + ':' + DQ + 'system' + DQ + ',' + DQ + 'content' + DQ + ':SYS},{' + DQ + 'role' + DQ + ':' + DQ + 'user' + DQ + ',' + DQ + 'content' + DQ + ':text}], ' + DQ + 'think' + DQ + ': False, ' + DQ + 'stream' + DQ + ': False, ' + DQ + 'options' + DQ + ': {' + DQ + 'num_ctx' + DQ + ': NUM_CTX, ' + DQ + 'temperature' + DQ + ': TEMPERATURE}}).encode(' + DQ + 'utf-8' + DQ + ')')
line('    url = OLLAMA_BASE + ' + DQ + '/api/chat' + DQ)
line('    req = urllib.request.Request(url, data=payload, headers={' + DQ + 'Content-Type' + DQ + ': ' + DQ + 'application/json' + DQ + '})')
line('    for attempt in range(retries):')
line('        try:')
line('            with urllib.request.urlopen(req, timeout=180) as resp:')
line('                result = json.loads(resp.read())')
line('                content = result.get(' + DQ + 'message' + DQ + ', {}).get(' + DQ + 'content' + DQ + ', ' + DQ + DQ + ')')
line('                if content: return content')
line('        except urllib.error.URLError as e:')
line('            print(' + DQ + '  [retry {}/{}] URLError: {}' + DQ + '.format(attempt+1, retries, e))')
line('            time.sleep(3 * (attempt + 1))')
line('        except Exception as e:')
line('            print(' + DQ + '  [retry {}/{}] {}: {}' + DQ + '.format(attempt+1, retries, type(e).__name__, e))')
line('            time.sleep(3 * (attempt + 1))')
line('    return ' + DQ + '[翻译失败] ' + DQ + ' + text[:200]')
line('')
line('def parse_chapter(item):')
line('    soup = BeautifulSoup(item.get_content(), ' + DQ + 'html.parser' + DQ + ')')
line('    title = ' + DQ + DQ)
line('    for h in soup.find_all([' + DQ + 'h1' + DQ + ',' + DQ + 'h2' + DQ + ',' + DQ + 'h3' + DQ + ']):')
line('        h_t = h.get_text(strip=True)')
line('        if h_t and len(h_t) < 200: title = h_t')
line('    raw = []')
line('    for x in soup.find_all(' + DQ + 'p' + DQ + '):')
line('        text = x.get_text(' + DQ + ' ' + DQ + ', strip=True)')
line('        if not text: continue')
line('        imgs = []')
line('        for img in x.find_all(' + DQ + 'img' + DQ + '):')
line('            src = img.get(' + DQ + 'src' + DQ + ') or img.get(' + DQ + 'epub:src' + DQ + ') or ' + DQ + DQ)
line('            alt = img.get(' + DQ + 'alt' + DQ + ') or ' + DQ + DQ)
line('            if src: imgs.append((src, alt))')
line('        raw.append((text, imgs))')
line('    end_chars = chr(46)+chr(33)+chr(63)+chr(59)+chr(58)+chr(34)+chr(41)+chr(93)+chr(12290)+chr(65281)+chr(65311)+chr(65306)+chr(12301)+chr(12299)')
line('    paragraphs = []')
line('    buf_t = ' + DQ + DQ)
line('    buf_i = []')
line('    for text, imgs in raw:')
line('        if not buf_t: buf_t = text; buf_i = list(imgs); continue')
line('        last = buf_t.rstrip()[-1] if buf_t.rstrip() else ' + DQ + DQ)
line('        if last in end_chars:')
line('            paragraphs.append((buf_t, buf_i))')
line('            buf_t = text; buf_i = list(imgs)')
line('        else:')
line('            buf_t = buf_t + ' + DQ + ' ' + DQ + ' + text')
line('            buf_i.extend(imgs)')
line('    if buf_t: paragraphs.append((buf_t, buf_i))')
line('    return title, paragraphs')
line('')
line('def render_bilingual_md(title, items, img_start=1):')
line('    lines = [' + DQ + '# ' + DQ + ' + title, ' + DQ + DQ + ']')
line('    idx = img_start')
line('    for it in items:')
line('        imgs = it.get(' + DQ + 'images' + DQ + ') or []')
line('        for src, alt in imgs:')
line('            lines.append(' + DQ + '![' + DQ + ' + ' + DQ + '图片 %02d: %s' + DQ + ' % idx + ' + DQ + '](' + DQ + ' + ' + DQ + 'images/' + DQ + ' + Path(src).name + ' + DQ + ')' + DQ + ')')
line('            lines.append(' + DQ + '<!-- 原 EPUB: src=%s, alt=%r -->' + DQ + ' % (src, alt))')
line('            lines.append(' + DQ + DQ + ')')
line('            idx += 1')
line('        lines.append(' + DQ + '> **原文**: ' + DQ + ' + it[' + DQ + 'original' + DQ + '])')
line('        lines.append(' + DQ + DQ + ')')
line('        lines.append(' + DQ + '> **译文**: ' + DQ + ' + it[' + DQ + 'translation' + DQ + '])')
line('        lines.append(' + DQ + DQ + ')')
line('    lines.append(' + DQ + '---' + DQ + ')')
line('    lines.append(' + DQ + DQ + ')')
line('    lines.append(' + DQ + '### 校对状态: 待校对' + DQ + ')')
line('    lines.append(' + DQ + DQ + ')')
line('    return chr(10).join(lines)')
line('')
line('def save_progress(prog):')
line('    PROGRESS_FILE.parent.mkdir(parents=True, exist_ok=True)')
line('    PROGRESS_FILE.write_text(json.dumps(prog, ensure_ascii=False, indent=2), encoding=' + DQ + 'utf-8' + DQ + ')')
line('')
line('def main():')
line('    ap = argparse.ArgumentParser()')
line('    ap.add_argument(' + DQ + 'spine_index' + DQ + ', type=int, nargs=' + DQ + '?' + DQ + ', default=1)')
line('    ap.add_argument(' + DQ + 'max_paragraphs' + DQ + ', type=int, nargs=' + DQ + '?' + DQ + ', default=None)')
line('    ap.add_argument(' + DQ + '--reset' + DQ + ', action=' + DQ + 'store_true' + DQ + ')')
line('    ap.add_argument(' + DQ + '--show-only' + DQ + ', action=' + DQ + 'store_true' + DQ + ')')
line('    a = ap.parse_args()')
line('    CHAPTERS_DIR.mkdir(parents=True, exist_ok=True)')
line('    IMAGES_DIR.mkdir(parents=True, exist_ok=True)')
line('    book = epub.read_epub(EPUB_PATH)')
line('    if a.spine_index >= len(book.spine): print(' + DQ + 'ERROR OOR' + DQ + '); sys.exit(1)')
line('    sid, _ = book.spine[a.spine_index]')
line('    item = book.get_item_with_id(sid)')
line('    if not item: print(' + DQ + 'ERROR no item' + DQ + '); sys.exit(1)')
line('    cid = ' + DQ + '%02d_%s' + DQ + ' % (a.spine_index, Path(item.get_name()).stem)')
line('    title, paragraphs = parse_chapter(item)')
line('    print(' + DQ + '[%02d] %s title=%r paragraphs=%d' + DQ + ' % (a.spine_index, item.get_name(), title, len(paragraphs)))')
line('    if a.max_paragraphs: paragraphs = paragraphs[:a.max_paragraphs]; print(' + DQ + '  limit=%d' + DQ + ' % a.max_paragraphs)')
line('    prog = json.loads(PROGRESS_FILE.read_text(encoding=' + DQ + 'utf-8' + DQ + ')) if PROGRESS_FILE.exists() else {}')
line('    if a.reset and cid in prog: del prog[cid]; save_progress(prog); print(' + DQ + '  reset' + DQ + ')')
line('    ch = prog.get(cid, {' + DQ + 'items' + DQ + ':[], ' + DQ + 'done' + DQ + ':False, ' + DQ + 'title' + DQ + ':title})')
line('    items = ch.get(' + DQ + 'items' + DQ + ', [])')
line('    if a.show_only:')
line('        if not items: print(' + DQ + '  empty' + DQ + '); return')
line('        md = render_bilingual_md(title or item.get_name(), items)')
line('        (CHAPTERS_DIR / (cid + ' + DQ + '.md' + DQ + ')).write_text(md, encoding=' + DQ + 'utf-8' + DQ + ')')
line('        print(' + DQ + '  rendered' + DQ + '); return')
line('    if ch.get(' + DQ + 'done' + DQ + '): print(' + DQ + '  done (use --reset)' + DQ + '); return')
line('    t0 = time.time()')
line('    for i, (pt, imgs) in enumerate(paragraphs):')
line('        if i < len(items): print(' + DQ + '  [%02d/%d] cached' + DQ + ' % (i+1, len(paragraphs))); continue')
line('        print(' + DQ + '  [%02d/%d] translating: %r' + DQ + ' % (i+1, len(paragraphs), pt[:50]))')
line('        ts = time.time()')
line('        tr = translate_one(pt)')
line('        dt = time.time() - ts')
line('        items.append({' + DQ + 'original' + DQ + ': pt, ' + DQ + 'translation' + DQ + ': tr, ' + DQ + 'images' + DQ + ': imgs})')
line('        prog[cid] = {' + DQ + 'items' + DQ + ': items, ' + DQ + 'done' + DQ + ': False, ' + DQ + 'title' + DQ + ': title}')
line('        save_progress(prog)')
line('        print(' + DQ + '             [%.1fs]' + DQ + ' % dt)')
line('    print(' + DQ + 'total: %.1fs' + DQ + ' % (time.time()-t0))')
line('    md = render_bilingual_md(title or item.get_name(), items)')
line('    (CHAPTERS_DIR / (cid + ' + DQ + '.md' + DQ + ')).write_text(md, encoding=' + DQ + 'utf-8' + DQ + ')')
line('    prog[cid][' + DQ + 'done' + DQ + '] = True')
line('    save_progress(prog)')
line('    print(' + DQ + 'done!' + DQ + ')')
line('')
line('if __name__ == ' + DQ + '__main__' + DQ + ':')
line('    main()')
out = r'D:\personalprofile\电子书\大雁塔\translate_epub\translate.py'
open(out, 'w', encoding='utf-8').write(NL.join(L))
print('OK size', len(NL.join(L)))